Super awesome formula edit
product-os/jellyfish-plugin-product-os pull request #566
Opened 2021-11-18 19:52 UTC by danthegoodman1

2021-11-18 19:52 UTC, danthegoodman1 commented
@balena-ci rebase

2021-11-18 19:56 UTC, danthegoodman1 commented
@Hades32 squashed to 1 commit and ready to go

2021-11-18 20:17 UTC, Hades32 requested changes
basically LGTM, but I just remembered that we said, we want to move this type to its own repo as otherwise a type from a plugin would reference an "external" type (i.e. `type-product-os-t-test-run`). This should also make rolling out this change much less "dangerous".

2021-11-18 20:17 UTC, Hades32 commented on lib/cards/service-source.ts
> +														 b.type.startsWith("t-product-os-test-run") &&
```suggestion
														 b.type.startsWith("type-product-os-t-test-run@") &&
```

2021-11-18 20:56 UTC, danthegoodman1 commented
@balena-ci rebase

2021-11-18 21:57 UTC, danthegoodman1 commented
> basically LGTM, but I just remembered that we said, we want to move this type to its own repo as otherwise a type from a plugin would reference an "external" type (i.e. `type-product-os-t-test-run`). This should also make rolling out this change much less "dangerous".
> 
> If you do that, you can also migrate `type-product-os-t-test-run` to use `type-source`

I thought that was to be in a separate PR, my mistake, I'll get that handled right away.

2021-11-19 12:33 UTC, danthegoodman1 commented
@balena-ci rebase

2021-11-19 13:19 UTC, danthegoodman1 commented
See https://github.com/product-os/t-service-source/pull/1

2021-11-19 14:15 UTC, closed without merging